README.md
githooks/commit-msg
setup.bat

Git hook to check committer name is not spudulike. Relates to https://github.com/ISISComputingGroup/IBEX/issues/3081

Add a git hook to ensure spudulike does not commit

---

README.md

The docs server was pointing at my fork on github since the docs hadn't been merged onto master yet.  Now that master has docs, I've changed the link in the readme to always point at the latest version.

Have readme always point at the latest docs

---

.travis.yml
general/scans/defaults.py
general/scans/fit.py
general/scans/monoid.py
general/scans/scans.py
instrument/loq/__init__.py
instrument/loq/sans.py
instrument/loq/scans.py
technique/sans/instrument.py

This adds some of the skeleton code for the LOQ beam line.  We'll need to fill in the details before it can be used in production.

Add LOQ beam line

---

requirements.txt
technique/muon/muon_begin_end.py
technique/muon/run_control.py
technique/muon/tests/test_muon_begin_end.py
technique/muon/tests/test_run_control.py

THIS MUST BE REVIEWED BY SOMEONE FROM COMPUTING
Added the relevant pre_cmd functions to hook into begin and end commands to check run information and titles and allow the user to changed them where required.
https://github.com/ISISComputingGroup/IBEX/issues/4913
---

Ticket4913 muon begin end commands

---

technique/muon/muon_begin_end.py
technique/muon/tests/test_muon_begin_end.py

Edited pre and post commands to make use of new `quiet` argument.
Added tests for new functionality.
See ticket [5102](https://github.com/ISISComputingGroup/IBEX/issues/5102) for details.

Ticket5102 add quiet argument to end command

---

CODEOWNERS

As a developer I do not want it to look like someone is reviewing a ticket that they aren't. Setting the code owners automatically adds developers as a reviewer. This is fine when done for some folders where the code does belong to someone but we don't need a default.
To test confirm that subsequent PRs (e.g https://github.com/ISISNeutronMuon/InstrumentScripts/pull/54) do not have a default reviewer. Once this is merged delete https://github.com/ISISNeutronMuon/InstrumentScripts/pull/54 without merging and remove associated branch.

Removed default Codeowners

---

technique/muon/muon_begin_end.py

EMU requested to have a timestamped print of when a run is beginning and ending. They also wanted the title to be constructed with T= and F= in front of the temp and field

Printing begin and end of run. Adding T= and F= to title.

---

.gitignore
technique/muon/background_plot.py

Muons
Added CSV reader/writer, with logic to check whether the data matches the first data points collected after IOC boots.
The skeleton structure has been added to the `BackgroundPlot` class, with implementation details added in `BackgroundBlockPlot`.
https://github.com/ISISComputingGroup/IBEX/issues/5284
Describing the testing undertaken for this PR
Follow instructions to make a background plotting script here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Background-Script-IOC
---

Ticket5284

---

general/utilities/__init__.py
general/utilities/hardware_communication.py

See https://github.com/ISISComputingGroup/IBEX/issues/5457
Effectively just copied from `genie_python` and fixed for python 3. Hard to write tests as very dependent on external server.
I tested by running
```python
#!/usr/bin/env python3
import socket
HOST = '127.0.0.1'  # Standard loopback interface address (localhost)
PORT = 65432        # Port to listen on (non-privileged ports are > 1023)
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
s.bind((HOST, PORT))
s.listen()
conn, addr = s.accept()
with conn:
print('Connected by', addr)
while True:
data = conn.recv(1024)
if not data:
break
conn.sendall(data)
```
In a separate process and then calling `print(send_tcpip("hi", '127.0.0.1', 65432, True))` and confirming that "hi" is returned. 
---

Created send_tcpip to help talk directly to hardware

---

instrument/crisp/scans.py
instrument/demo/scans.py
instrument/surf/scans.py

SURF and CRISP
Populate was removed in favour of `b.` but we missed that instruments import this as a function in their scripts so this corrects that
Remove populate references
None found during debug
do `from instrument.<instrument> import *`
where <instrument> is surf or crisp or demo
---

Remove populate from instruments which was missed in original remove popluate

---

ChangeLog
general/scans/motion.py

general/scans/motion.py
- As an instrument scientist I want the units of a block to be accessible through the api, this is needed when creating graphs with units on (and probably other places too)
Units for a block are now accessible directly through the API.
Moved the `Motion/get_units` function to `genie_epics_api`, renamed to `get_block_units` to be used in `get_block_data` for `g.cget()` 
https://github.com/ISISComputingGroup/IBEX/issues/5620
Block units are displayed in the output dictionary from `g.cget("<blockname>")`
In IBEX GUI Scripting perspective run the `g.cget()` command on a block. The block's unit (if it has one) should be displayed under the value e.g. `('unit', 'Hz'),`. If block does not have a unit, it will be an empty string e.g `('unit', ''),`.
---

5620: Moved Motion.get_units to genie_epics_api

---

general/utilities/restart_ioc_when_pv_in_alarm.py

General, used for DAQmx on EMU
See ticket
Script for the backgroundscript IOC which restarts an IOC if it becomes disconnected. 
See ISISComputingGroup/IBEX#5710
Manual tests so far, ISISComputingGroup/IBEX/issues/5743 has been created to system test. 
Check that when the IOC goes into an invalid alarm state the IOC is restarted. 
---

Ticket5710: Restart IOC when in alarm

---

general/utilities/button_functions.py
general/utilities/test/test_button_function.py

POLREF initially but all instruments
Allow a user to run a python script from a PV or OPI.
add button function adds functionality to background ioc ability to monitor pvs
https://github.com/ISISComputingGroup/IBEX/issues/5410
See unit tests in pull request
Setup a background IOC with example script and make sure it can set stuff. On clicking go script should run.
- Make script update the status make sure this updates
- Make script crash, make sure stack trace is printed in IOC log
---

Button scripts

---

general/scans/defaults.py
general/scans/scans.py

All
Keyboard interrupts were not propagating to the top level of the python interpreter. i.e. `ctrl+c`-ing a scan running inside a loop would interrupt that specific call to `scan` but would then run the next iteration of the loop.
Keyboard interrupts are no longer ignored inside the scan command. Added an interrupt handler to ensure runs are stopped/aborted on interrupting a scan and number of periods are reverted to their value before the scan.
https://github.com/ISISComputingGroup/IBEX/issues/5785
Checked that no further code is executed in a loop when keyboard-interrupting a scan - see below.
Added automated system test: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/73
1. check out master branch of scans library
2. in the ibex client, go to the scripting console
3. run …

Ticket5785 interrupt

---

instrument/polref/scans.py

POLREF
POLREF still had the spectra definitions from CRISP in their scans setup file. These changes define the actual spectra ranges for all detectors (as taken from Mantid etc.)
Just updating some hardcoded values.

Fix POLREF spectra definitions

---

general/scans/fit.py
general/scans/test/test_fit.py

All
Make fits on the graphs show numbers to 4dp.
add tests and use smart number formatter consistently in all titles
Snags list  #61
Unit tests
Plot with fit
---

Set dp to 4dp consistently for all fits

---

general/scans/defaults.py
general/scans/plot_functions.py
general/scans/scans.py
general/scans/test/test_scans.py
instrument/crisp/scans.py
instrument/demo/scans.py
instrument/inter/scans.py
instrument/polref/scans.py
instrument/surf/scans.py

Make last scan read from script dir
All, but will only effect directly POLREF, SURF, CRISP and INTER
Scans should save data in the genie_python scrip folder and last_scan should read data from log_file directory.
Implement the above
https://github.com/ISISComputingGroup/IBEX/issues/5794
Unit
Run scan and make sure data is saved to genie_python script dir for the demo instrument.
Make sure last scan reads the data from that directory and that you can do last_scan(fit=Gaussian)
---

Make data in scans write to script dir by default

---

general/scans/defaults.py

All
There was a bug in the IBEX gui where when the perspective was switched directly after starting a scan, the matplotlib plot would pop up in the new perspective. We don't want this to happen.
Matplotlib plot is now created at the start of the scan instead of in the middle, which makes the window of opportunity for this bug to appear much shorter. If you are dedicated enough you can still reproduce the bug (i.e. switch perspective almost instantly as you run the scan) however it's very unlikely to happen by accident so I think this should be an acceptable solution.
https://github.com/ISISComputingGroup/IBEX/issues/5848
/
1. In your instrument startup script (`init_<inst>.py`) add the following:
```
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(r"C:\\", …
```

Create fig first in scan

---

general/utilities/io.py
technique/reflectometry/__init__.py
technique/reflectometry/base.py
technique/reflectometry/test/test_base.py

SURF, INTER
SURF and INTER have a laser height gun installed above the sample point that provides a readout of the relative sample height. They would like to have an IBEX-equivalent to the OpenGENIE auto height function using this laser to automatically realign a sample. That function looks as follows:
```
PROCEDURE autoheight
LOCAL targetKeyence currentKeyence difference height targetHeight
targetKeyence = 0.0
currentKeyence = cshow(keyence)
currentKeyence = currentKeyence[1]
difference = currentKeyence-targetKeyence
height = cshow("fine_Z")
height = height[1]
IF (currentKeyence < 0)
targetHeight = height + abs(difference)
ELSE
targetHeight = height - abs(difference)
ENDIF
printn "target Height" + As_string(targetHeight)
cset fine_z = targetHeight
ENDPROCEDURE 
```
Notes (checked with …

Add auto height function

---

technique/reflectometry/instrument_constants.py

IOC prefix in function getting reflectometry constants was outdated, this fixes it. Not sure how this has not been caught until now.

Fix IOC prefix

---

technique/reflectometry/base.py

INTER
INTER do not always want to add current slit gap values to their run title.
Add parameter to `run_angle` and `transmission` scripts to make slit gaps in title optional.

add parameter for adding gaps to run title

---

technique/reflectometry/base.py

INTER
run_angle script sets height correctly in INTER
Height blocks that run_angle was trying to write to were non-existent. Blocks were renamed to something that caters to INTER's naming scheme and is actually available.
https://github.com/ISISComputingGroup/IBEX/issues/6499
Describing the testing undertaken for this PR
Explain how the reviewer can test the changes made e.g. what state they need to be in do the tests
---

Fix inter run angle script not setting any height

---

instrument/sans2d/__init__.py
instrument/sans2d/sans.py
instrument/sans2d/scans.py

Sans2D
This PR should only be accepted if it will enable SANS2D to perform SANS measurements using the same interface as Larmor, Zoom, and LOQ.  This includes properly setting Aperture 6, which is *not* no supported in the current draft.  
After discussion with Sarah Rogers, I have set up the detector settings for SANS2D.  I have also enabled detector power checking (with an error alert for an unpowered detector), vaccuum shutter status, and slit value checks.
There is no ticket
Unfortunately, this can only be tested on the beamline.
This can only be tested on the SANS2D beamline by running a SANS measurement.
---

Enable IBEX on Sans2D

---

general/utilities/restart_ioc_when_pv_in_alarm.py

Changed the `restart_ioc_when_pv_in_alarm` script to return a stoppable thread.
https://github.com/ISISComputingGroup/IBEX/issues/7291
See ticket.
See ticket.
---

Ticket7291

---

technique/muon/tektronix_osc_screenshots.py
technique/muon/tests/test_tektronix_osc_screenshots.py

Muons, Osc was taken from EMU but I'm fairly sure other instruments want similar functionality. 
As a user, I want to be able to run a script background script that takes an image from the oscilloscope every 10 minutes and saves it into the archive as a `.png`. 
Adds the described script, allowing
ISISComputingGroup/IBEX#7318
1. Boot up the IBEX server
2. Run the script with the oscilloscope off
3. Check that the appropriate error message is shown when it can't connect
4. Boot the oscilloscope
5. Put the IP address into the script constants and drop the time bettween screenshots to a few seconds
6. Run the script again, this time checking that a zip file is created with a dir inside that contains the oscilloscope images. They should be marked with the rb number and a timestamp. 
Partially …

Create Background Script for Tektronix Oscilloscope Screenshots

---

instrument/loq/sans.py
instrument/sans2d/sans.py
instrument/zoom/sans.py
technique/sans/instrument.py

Fixes to refactored do_sans/trans routines that we made to make it work while commissioning on ZOOM
- Added checks to protect against scripts falling over if DLS motion setpoints are not set up (can be removed once this is done for LOQ, SANS2D, ZOOM)
- renamed `position` argument to `pos`, requested by ZOOM scientists to keep with their naming convention throughout existing scripts. This was a new addition in https://github.com/ISISComputingGroup/IBEX/issues/7132 so should not break anything
- fixed Monitor 4 PV writes
- fixed get_pv/send_pv (it failed previously when appending the prefix, not sure why, this seems a bit neater either way)

Do_sans/trans Fixes for ZOOM

---

technique/sans/instrument.py

`do_sans` was changed to use pos instead of position as a parameter name at the request of instrument scientists [here](https://github.com/ISISNeutronMuon/InstrumentScripts/pull/100), however `do_trans` was missed and should also be updated. This pull request does so.

change do_trans to use pos to match do_sans

---

instrument/loq/sans.py
instrument/sans2d/sans.py
technique/sans/instrument.py

SANS instruments
Remove default values from certain methods, which overwrote thickness and title if not specified
[Ticket7908](https://github.com/ISISComputingGroup/IBEX/issues/7908)
Be confident that when do_sans/do_trans/measure functions called, title and thickness are not overwritten unless set to.
---

Ticket7908 correct default behaviour

---

technique/muon/caen_thresholds.py

North-side muons
As an instrument scientist, I have a large number of thresholds to be set (100+) and would like to be able to load them from a file rather than inputting each manually.
Script created based on parameters from a legacy script used by the scientists under SECI. Additional funtionality added to allow for tweaking thresholds by set amounts.
[8170](https://github.com/ISISComputingGroup/IBEX/issues/8170)
Manual testing on CHRONUS and ARGUS
- set up a simulated CAEN
- run the script
- check it alters thresholds as appropriate
---

Ticket8170 caen thresholds
