doc/source/sans/tutorial.rst, doc/source/scans/tutorial.rst, general/scans/detector.py, general/scans/mocks.py, general/scans/motion.py, instrument/larmor/__init__.py, instrument/larmor/sans.py, instrument/larmor/scans.py, instrument/larmor/util.py, technique/sans/genie.py, technique/sans/util.py
This pull request contains the changes made to the code on the Larmor beam line during the most recent run cycle.  It includes bug fixes and minor helper functions.
The code has been tested and linted before submission.
=> Local changes from Cycle 18/02

doc/source/conf.py, doc/source/index.rst, doc/source/sans/index.rst, doc/source/scans/index.rst, doc/source/scans/instrument.rst
The presence of unicode characters in the documentation prevented the generation of PDF of the documentation.  The docs have been updated to ensure that the PDF generation works.
=> Produce printable pdf documentation

doc/source/sans/tutorial.rst, general/scans/detector.py, instrument/zoom/sans.py, instrument/zoom/scans.py, technique/sans/util.py
These are the updates that needed to be made on Zoom to bring the instrument into operation for cycle 18/4.  While most of the changes were specific to the beamline, the following general changes were made:
1) The specific_spectra function is now robust against the failure of the genie.get_spectrum function
2) The sans module no longer attempts to memoize the the current instrument state.  This had caused serious problems when the expected state lost sync with the actual state.
=> Zoom updates

ChangeLog, general/scans/fit.py
Implements a more sophisticated algorithm for finding a first guess of peak centre and width for the Gaussian fit.
=> better algorithm for Gaussian fit first guess centre and sigma

ChangeLog, doc/source/scans/tutorial.rst, general/scans/motion.py
=> Add case insensitivity to BlockMotion

ChangeLog, general/scans/fit.py
=> Mandate colour of vertical line for Centre of Mass fit.

technique/muon/muon_begin_end.py
Muon request to surround previously set values with brackets.
=> Use brackets around muon already set values

.github/pull_request_template.md
https://github.com/ISISComputingGroup/IBEX/issues/5184
Check that the specified template contains logical fields.
Check that when creating a new PR this template is used.
=> Implement a pull request template

technique/muon/background_plot.py
For https://github.com/ISISComputingGroup/IBEX/issues/5015
See https://github.com/ISISNeutronMuon/InstrumentScripts/wiki/Muon
Create a updating background plot.
=> Ticket5015 continous graph

general/scans/detector.py, general/scans/fit.py, general/scans/monoid.py, general/scans/scans.py, technique/reflectometry/base.py, technique/reflectometry/contrast_change.py, technique/reflectometry/refl_scans.py
Surf and Crisp
https://github.com/ISISComputingGroup/IBEX/issues/5282
- Abort transmission does not exit after ctr+c and end (exception is not rethrown)
( Keyboard interruption exception needs rethrowing after user chooses what to do abort, continue or reset). So I can do `for i in range(10): technique.reflectometry.transmission(mysample, "title", 10, 20, count_frames=300)` and it will quit
- ctrl + c in top of scans script should do the same as if used in body
- this is before the scan starts proper in the pause setup
- Plot data should be written to u:
- Legend on graphs needs to be at top not obscuring graph
- Print fit after scan (even if the parameter is capture)
Fix the minor errors above
https://github.com/ISISComputingGroup/IBEX/issues/5282
Developer testing
Check each of the …
=> Ticket5282 script fix from testing

instrument/sans2d/__init__.py, instrument/sans2d/sans.py
SANS2D
https://github.com/ISISComputingGroup/IBEX/issues/4591
Adds basic config for SANS2D, based on ZOOM config
Notes:
- Changing number of periods to 1 is done by the base class
- The fast shutter is now automatically opened/closed by the begin/end commands so don't need these explicitly
n/a this is just a configuration file
---
=> Add configuration for SANS2D

general/scans/mocks.py, general/scans/motion.py, instrument/polref/__init__.py, instrument/polref/scans.py, technique/reflectometry/sample.py
POLREF, all reflectometrs
https://github.com/ISISComputingGroup/IBEX/issues/5424
Add script for POLREF to run the reflectometry code.
Fix an issue in the get unit which changed with the latest genie_python release
https://github.com/ISISComputingGroup/IBEX/issues/5424
Ran scan locally on instrument setup to look like POLREF (because of state of instrument only get to check run state but it should work)
Make your instrument look like POLREF and run the scan command.
---
=> Polref instrument script

instrument/inter/__init__.py, instrument/inter/scans.py
INTER
Config for INTER scan
Config needed to make scans work on inter
https://github.com/ISISComputingGroup/IBEX/issues/5530
Should be able to run scan on inter
Run scan.
---
=> Inter scans definition

instrument/loq/sans.py, technique/sans/instrument.py
LOQ
Local changes had been made now copying them in to the remote repo. Changes give DAE change when selecting sans routines and extra sample positions
https://github.com/ISISComputingGroup/IBEX/issues/5689
- Worked on instrument tested with scientist
- Not needed already tested
---
=> Adding ranges and changing tables

instrument/sans2d/sans.py, instrument/sans2d/scans.py
SANS2D
https://github.com/ISISComputingGroup/IBEX/issues/5698
https://github.com/ISISComputingGroup/IBEX/issues/5698
https://github.com/ISISComputingGroup/IBEX/issues/5698
n/a config file only
This will need testing on a beamline with neutrons and the results comparing with SECI. As we cannot run the GCL code we don't have anything to compare against for the moment, so just check the conversion looks sensible.
---
=> Ticket5698

doc/source/sans/guide.rst, instrument/larmor/sans.py, instrument/loq/sans.py, instrument/sans2d/sans.py, instrument/zoom/sans.py, technique/sans/util.py
See https://github.com/ISISComputingGroup/IBEX/issues/5791
* Checkout zoom's config
* On master:
* Call do_sans('test', dae='event')
* Call dotrans()
* Note wiring table and change it manually to a different one
* Call do_sans('test', dae='event')
* Confirm wiring table is still trans one
* On this branch:
* Do the above and confirm second do_sans actually changes the wiring table
* Confirm that calling do_sans again does not take a significant amount of time
---
=> Ticket 5791: Remove caching of SANS/TRANS

general/scans/test/test_util.py
None
Test utils (stride was broken and I fixed it and wrote these tests but forgot to commit them)
Test some util functions
N/A
N/A
Run tests
---
=> Test stride

doc/source/scans/instrument.rst, general/scans/defaults.py, general/scans/fit.py, general/scans/monoid.py, general/scans/plot_functions.py, general/scans/scans.py, general/scans/test/test_fit.py, general/scans/test/test_plot_functions.py, instrument/larmor/scans.py
All
- If a fit fails this should not stop a scan from completing.
- Also while I was in set up plot size for markers
- Surround fitting actions use of the fit with exception handling to avoid crashes on main plot
- Fix issue on quality fit where array isn't a numpy array so crashes
- Add a default plot functions and refactor away some of the plotting code from fit action and main plot action
https://github.com/ISISComputingGroup/IBEX/issues/5795
See tests
Try scanning across a range with a top hat fit
---
=> Ticket5795 robust scans

technique/reflectometry/contrast_change.py
Fixed a mistake where the contrast change script never actually started pumping after setting target pump time/volume.
=> Fix contrast change script

general/scans/fit.py, general/scans/test/test_fit.py
All
I can fit a slit scan, which is a background and then a straight line on top. Always background on the left and high on the right.
Add fit function to fits based on curve fit.
https://github.com/ISISComputingGroup/IBEX/issues/6305
see pull request
Run a scan and fit with slit scan data, to make it better change the demo instrument to do this. Best of all try a slit scan on a real instrument.
---
=> Add slit scan fit

technique/muon/background_plot.py
Muons
Fixes the following in the background plotting:
* FuncAnimation was no longer working, spent ~1 hour trying to work out why but fell back on just doing it with our own threads
* The csv module does not preserve None values, instead converting them to empty strings. When reading back out it ignores the empty strings and so creates a list of values that's too short and can't be plotted. This causes the crash seen in the original ticket
* Tidied up the way that we pad to the right of the graph to make it more dynamic
See https://github.com/ISISComputingGroup/IBEX/issues/6347
* Copy the background_script file from MUSR's configuration area and set it up to plot a couple of blocks
* Start the background script IOC and open the plot in the scripting perspective of the GUI using …
=> Fix background plotting

general/scans/plot_functions.py, technique/muon/background_plot.py
Reflectometry, muons, others
https://github.com/ISISComputingGroup/IBEX/issues/6719
In conjunction with changes to the GUI and genie_python, make plotting much more reliable.
https://github.com/ISISComputingGroup/IBEX/issues/6719
See GUI PR for details
See GUI PR for details
---
=> Update instrumentscripts for new backend

.travis.yml, doc/source/sans/tutorial.rst, doc/source/scans/instrument.rst, doc/source/scans/tutorial.rst, general/scans/defaults.py, general/scans/scans.py, instrument/larmor/sans.py, instrument/loq/sans.py, instrument/sans2d/sans.py, instrument/zoom/sans.py, requirements.txt, technique/sans/genie.py, technique/sans/instrument.py, technique/sans/util.py
Closes: https://github.com/ISISComputingGroup/IBEX/issues/7132
Sans2d, Zoom, Larmor LOQ
Make the do_sans, and do_trans commands more useful and scripts more robust. 
Some refactoring around `measure`, `do_sans`, and `do_trans` to fit with requirements given by instrument scientists:
- do_sans() and do_trans() without any parameters will simply change the instrument into the relevant configuration 
- passing measure related parameters to the function causes it to undertake measurements e.g. time, uamps
- Parameters requested: title, position, thick, dae
`do_sans` and `do_trans` along with `measure` have been refactored to reflect these requirements and to be slightly more modular.
Other small improvements such as:
- Updated strings to be f strings
- Standardised most naming conventions
- …
=> 7132 improve do trans do sans scripts

instrument/larmor/SESANSroutines.py, instrument/larmor/sans.py, instrument/zoom/sans.py, instrument/zoom/util.py
This PR contains a few modifications for ZOOM and LARMOR that replicate several polarised measurement modes (SESANS, polarised SANS, and polarisation analysis) that were either included in the SANSroutines in C:\Instrument\Settings\config\NDX...\ or breadcrumbed in user scripts. 
The new instrument script code in this PR has not seen a test so far for functionality. Coded as seemed rationale and based on what already existed.
---
=> Local changes from ZOOM and LARMOR

technique/sans/instrument.py
Found these positions which were added but not yet committed on LARMOR
=> Add uncommitted positions from NDXLARMOR

general/scans/fit.py, instrument/loq/sample_changer_scan.py, instrument/loq/sans.py
Added uncommitted changes from LOQ
=> Loq local changes

githooks/commit-msg, setup.bat
https://github.com/ISISComputingGroup/IBEX/issues/7910
=> Removed commit hooks for the purpose of commit automation
